# Generated by Django 5.1.6 on 2025-03-11 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_productmodel_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="color",
            field=models.CharField(default='Sin color', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="dimensions",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="seller",
            field=models.CharField(default='N/A', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.FloatField(blank=0, null="null"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
