# Generated by Django 5.1.6 on 2025-03-11 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ecommerce",
            "0003_productmodel_color_productmodel_dimensions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="color",
            field=models.CharField(max_length=100, null="Sin color"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="description",
            field=models.TextField(null="Sin descripción"),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="dimensions",
            field=models.FloatField(null=0.0),
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="price",
            field=models.FloatField(default=0, null=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productmodel",
            name="seller",
            field=models.CharField(max_length=100, null="N/A"),
        ),
    ]
